services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - notify

  notify-provider:
    build:
      context: ./provider
    container_name: notify-provider
    command: "npx tsx server.ts"
    volumes:
      - ./provider:/app/
    ports:
      - "8071:8071"
      - "8072:8072"
      - "8073:8073"
      
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
    networks:
      - notify

  notify-server:
    build:
      context: ./server
    container_name: notify-server
    command: "./wait-for-it.sh rabbitmq:5672 -- yarn dev"
    volumes:
      - ./server:/app/
    ports:
      - "8080:8080"
    
    networks:
      - notify
    environment:
      - PORT=8080
      - RABBITMQURL=rabbitmq
      - SERVERHOST=notify-server
      - PROVIDERHOST=notify-provider

networks:
  notify:
    driver: bridge

volumes:
  rabbitmq-data:
